name: Hello World

on:
  workflow_dispatch:
  push:
    branches:
      - adf_publish

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, world"

