name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

############################################ NODE APPLICATION ######################################################

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: setting up the node application..
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: building and running the node application.
      run: npm install
           npm run build --if-present
           npm test

############################################ PYTHON AND FLASK CODE ###############################################

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     python-version: ["3.11"]

    # steps:
    # - name: Checkout Code
    #   uses: actions/checkout@v3
      
    # - name: running the python application
    #   run: |
    #     python3 app.py

    # - name: running the flask application
    #   run: |
    #     pip install -r requirements.txt
    #     export FLASK_APP=webapp.py
    #     nohup flask run --host=0.0.0.0 --port=5000 &

    # - name: testing the flask application
    #   run: |
    #     curl "http://localhost:5000"
        

